# Generated by Django 4.2 on 2024-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(verbose_name='сумма оплаты'),
        ),
    ]
