# Generated by Django 4.2 on 2024-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_payment_date_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка для оплаты'),
        ),
    ]
